### ISSUE TITLE
Getting error when running reek

### ISSUE THREAD

**Issue by ericgross** [troessner/reek#942]
When I run `reek` I get this:

```
/Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/smells/nested_iterators.rb:124:in `block in ignored_iterator?': undefined method `name' for #<#<Class:0x007ffb5131e328>:0x007ffb5131e2b0> (NoMethodError)
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/smells/nested_iterators.rb:124:in `any?'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/smells/nested_iterators.rb:124:in `ignored_iterator?'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/smells/nested_iterators.rb:115:in `increment_depth'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/smells/nested_iterators.rb:105:in `block in scout'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/smells/nested_iterators.rb:100:in `map'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/smells/nested_iterators.rb:100:in `scout'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/smells/nested_iterators.rb:105:in `block in scout'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/smells/nested_iterators.rb:100:in `map'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/smells/nested_iterators.rb:100:in `scout'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/smells/nested_iterators.rb:70:in `find_deepest_iterator'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/smells/nested_iterators.rb:48:in `inspect'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/smells/smell_detector.rb:47:in `run_for'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/smells/smell_repository.rb:47:in `block in examine'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/smells/smell_repository.rb:46:in `each'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/smells/smell_repository.rb:46:in `examine'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/examiner.rb:81:in `block in run'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/context/code_context.rb:85:in `each'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/context/code_context.rb:87:in `block in each'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/context/code_context.rb:86:in `each'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/context/code_context.rb:86:in `each'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/context/code_context.rb:87:in `block in each'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/context/code_context.rb:86:in `each'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/context/code_context.rb:86:in `each'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/examiner.rb:80:in `run'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/examiner.rb:37:in `initialize'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/cli/command/report_command.rb:24:in `new'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/cli/command/report_command.rb:24:in `block in populate_reporter_with_smells'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/cli/command/report_command.rb:23:in `each'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/cli/command/report_command.rb:23:in `populate_reporter_with_smells'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/cli/command/report_command.rb:15:in `execute'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.3/lib/reek/cli/application.rb:28:in `execute'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.3/bin/reek:13:in `<top (required)>'
	from /Users/eric/.rbenv/versions/2.3.1/bin/reek:23:in `load'
	from /Users/eric/.rbenv/versions/2.3.1/bin/reek:23:in `<main>'

```

I removed the .reek file assuming I botched it up, but it still gives the same error. My code passes rubocop, and it does still work. Any ideas how I can figure out what the issue is? The word "name" is pretty common in the code, so that's not much to go on.

**Comment by troessner** [comment]
How exactly are you running Reek and can you please paste the offending code?

**Comment by mvz** [comment]
This sounds very similar to the problem reported in this comment: https://github.com/troessner/reek/issues/836#issuecomment-222181329

**Comment by troessner** [comment]
We updated `parser`  but didnt release a new Reek version, on the road now, will do this later this evening.

**Comment by troessner** [comment]
I just released 4.0.4 with the parser upgrades - can you please check if the current version still doesn't work for you @ericgross ?

**Comment by ericgross** [comment]
Same issue after updating to 4.0.4:

`/Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.4/lib/reek/smells/nested_iterators.rb:139:in `block in ignored_iterator?': undefined method `name' for #<#<Class:0x007fd7ccadad58>:0x007fd7ccadace0> (NoMethodError)`

**Comment by troessner** [comment]
Yeah, thats exactly why Reek should catch ALL uncatched  exceptions at top level so that we can 1) debug such problems easier and 2.) Improve overall user experience. 
That is something I had on my agenda for quite a while now - i'll look into it and then we can revisit this issue.

**Comment by nachokb** [comment]
this is also happening to me... was using an old version, upgraded to 4.0.4 and it stopped working; I can't determine what is triggering this...

```bash
⚡ reek
$HOME/.rvm/gems/ruby-2.2.1/gems/reek-4.0.4/lib/reek/smells/nested_iterators.rb:139:in `block in ignored_iterator?': undefined method `name' for s(:lambda)
:#<Class:0x000000059b7670> (NoMethodError)
        from $HOME/.rvm/gems/ruby-2.2.1/gems/reek-4.0.4/lib/reek/smells/nested_iterators.rb:139:in `any?'
        from $HOME/.rvm/gems/ruby-2.2.1/gems/reek-4.0.4/lib/reek/smells/nested_iterators.rb:139:in `ignored_iterator?'
        from $HOME/.rvm/gems/ruby-2.2.1/gems/reek-4.0.4/lib/reek/smells/nested_iterators.rb:130:in `increment_depth'
        from $HOME/.rvm/gems/ruby-2.2.1/gems/reek-4.0.4/lib/reek/smells/nested_iterators.rb:110:in `block in scout'
        from $HOME/.rvm/gems/ruby-2.2.1/gems/reek-4.0.4/lib/reek/smells/nested_iterators.rb:109:in `each'
        from $HOME/.rvm/gems/ruby-2.2.1/gems/reek-4.0.4/lib/reek/smells/nested_iterators.rb:109:in `flat_map'
```

**Comment by mvz** [comment]
@nachokb that is a different bug, and I know exactly where it comes from. I'll look into it.

**Comment by nachokb** [comment]
@ericgross I found out which file was causing the issue by looking a `exp`, taking note of the variable, arguments and method names, and just being familiar with the codebase...

**Comment by mvz** [comment]
@troessner looking forward to your proposal on how to make this nicer for users.

**Comment by troessner** [comment]
@mvz I'll open up an issue for discussing this soon with an initial draft ;)

**Comment by ericgross** [comment]
In the mean time, is there any way I can get some version of reek working for me?

**Comment by troessner** [comment]
@ericgross I just released Reek 4.0.5 with contains #949 which should fix your problem.
Can you please try with the latest Reek version?

**Comment by ericgross** [comment]
Looks the same to me:

```
$ reek
/Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.5/lib/reek/smells/nested_iterators.rb:139:in `block in ignored_iterator?': undefined method `name' for #<#<Class:0x007f8cb4891668>:0x007f8cb48915f0> (NoMethodError)
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.5/lib/reek/smells/nested_iterators.rb:139:in `any?'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.5/lib/reek/smells/nested_iterators.rb:139:in `ignored_iterator?'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.5/lib/reek/smells/nested_iterators.rb:130:in `increment_depth'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.5/lib/reek/smells/nested_iterators.rb:110:in `block in scout'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.5/lib/reek/smells/nested_iterators.rb:109:in `each'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.5/lib/reek/smells/nested_iterators.rb:109:in `flat_map'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.5/lib/reek/smells/nested_iterators.rb:109:in `scout'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.5/lib/reek/smells/nested_iterators.rb:115:in `block in scout'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.5/lib/reek/smells/nested_iterators.rb:109:in `each'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.5/lib/reek/smells/nested_iterators.rb:109:in `flat_map'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.5/lib/reek/smells/nested_iterators.rb:109:in `scout'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.5/lib/reek/smells/nested_iterators.rb:86:in `find_candidates'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.5/lib/reek/smells/nested_iterators.rb:74:in `find_violations'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.5/lib/reek/smells/nested_iterators.rb:47:in `inspect'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.5/lib/reek/smells/smell_detector.rb:47:in `run_for'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.5/lib/reek/smells/smell_repository.rb:47:in `block in examine'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.5/lib/reek/smells/smell_repository.rb:46:in `each'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.5/lib/reek/smells/smell_repository.rb:46:in `examine'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.5/lib/reek/examiner.rb:81:in `block in run'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.5/lib/reek/context/code_context.rb:85:in `each'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.5/lib/reek/context/code_context.rb:87:in `block in each'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.5/lib/reek/context/code_context.rb:86:in `each'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.5/lib/reek/context/code_context.rb:86:in `each'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.5/lib/reek/context/code_context.rb:87:in `block in each'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.5/lib/reek/context/code_context.rb:86:in `each'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.5/lib/reek/context/code_context.rb:86:in `each'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.5/lib/reek/examiner.rb:80:in `run'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.5/lib/reek/examiner.rb:37:in `initialize'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.5/lib/reek/cli/command/report_command.rb:24:in `new'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.5/lib/reek/cli/command/report_command.rb:24:in `block in populate_reporter_with_smells'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.5/lib/reek/cli/command/report_command.rb:23:in `each'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.5/lib/reek/cli/command/report_command.rb:23:in `populate_reporter_with_smells'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.5/lib/reek/cli/command/report_command.rb:15:in `execute'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.5/lib/reek/cli/application.rb:28:in `execute'
	from /Users/eric/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/reek-4.0.5/bin/reek:13:in `<top (required)>'
	from /Users/eric/.rbenv/versions/2.3.1/bin/reek:23:in `load'
	from /Users/eric/.rbenv/versions/2.3.1/bin/reek:23:in `<main>'

```

**Comment by troessner** [comment]
Does disabling the NestedIterator detector in your configuration a la

```yaml
NestedIterators:
  enabled: false
```

at least make Reek work again?

If it doesnt I'm afraid you'll have to wait for:

>> Yeah, thats exactly why Reek should catch ALL uncatched exceptions at top level so that we can 1) debug such problems easier and 2.) Improve overall user experience. 
That is something I had on my agenda for quite a while now - i'll look into it and then we can revisit this issue.

**Comment by ericgross** [comment]
Disabling the `NestedIterators` smell did fix my problem. Thank you for getting me going while you guys figure out the big issues in play!

**Comment by troessner** [comment]
Glad we worked this out @ericgross!

**Comment by troessner** [comment]
------ This one is put on hold until we implemented #953  --------

**Comment by Ross-Hunter** [comment]
Same issue here, same fix worked. 👍

**Comment by troessner** [comment]
#953 is being discussed right now AND I'm on vacation in the, uhm, solitude of Iceland so chances that this gets implemented soon so we can drill down to the root cause are really high ;)

**Comment by troessner** [comment]
WIP in #996

**Comment by troessner** [comment]
@ericgross && @nachokb we just released 4.2.4. which contains #996 
Could you please run this Reek version on your source in question?
It should point us to the problematic code ;)

**Comment by Ross-Hunter** [comment]
Nested iterator smell works now. It was blowing up as described above in 4.1. It works in 4.2.3, and in 4.2.4 I get additional exceptions about syntax errors.

Custom Rails generators might be the source of the problem. They are actually `.erb` files, but you have to name them `.rb` otherwise Rails doesn't recognize them 😦 

👍  Thanks!

**Comment by ericgross** [comment]
Looks good to me, thanks!

**Comment by mvz** [comment]
@ericgross:
> Looks good to me, thanks!

Do you mean you don't get any error anymore, even with NestedIterator enabled?

@Ross-Hunter:
> in 4.2.4 I get additional exceptions about syntax errors.

Does the output give you enough information to exclude the offending files?

**Comment by Ross-Hunter** [comment]
> Does the output give you enough information to exclude the offending files?

Yeah.

**Comment by ericgross** [comment]
now i am getting proper errors in the offending files.

**Comment by troessner** [comment]
>> now i am getting proper errors in the offending files.

and

>>
Does the output give you enough information to exclude the offending files?
Yeah.

Can you c&p those here?

**Comment by Ross-Hunter** [comment]
```
09:37:57 - INFO - Running reek for files: 'lib/', 'app/', 'spec/'
lib/generators/migration.rb:1:7: error: unexpected token tLT
lib/generators/migration.rb:1: class <%= migration_class_name %> < ActiveRecord::Migration[<%= ActiveRecord::Migration.current_version %>]
lib/generators/migration.rb:1:       ^
lib/generators/migration.rb: Parser::SyntaxError: unexpected token tLT
lib/generators/policy/templates/policy.rb:1:7: error: unexpected token tLT
lib/generators/policy/templates/policy.rb:1: class <%= file_name.classify %>Policy < ApplicationPolicy
lib/generators/policy/templates/policy.rb:1:       ^
lib/generators/policy/templates/policy.rb: Parser::SyntaxError: unexpected token tLT
lib/templates/rails/scaffold_controller/api_controller.rb:1:1: error: unexpected token tLT
lib/templates/rails/scaffold_controller/api_controller.rb:1: <% if namespaced? -%>
lib/templates/rails/scaffold_controller/api_controller.rb:1: ^
lib/templates/rails/scaffold_controller/api_controller.rb: Parser::SyntaxError: unexpected token tLT
lib/templates/rspec/request/request_spec.rb:6:54: error: unexpected token tIDENTIFIER
lib/templates/rspec/request/request_spec.rb:6:   let(:org_<%=plural_table_name%>) { create_list :<%=singular_table_name%>, 3, organization: organization }
lib/templates/rspec/request/request_spec.rb:6:                                                      ^~~~~~~~~~~~~~~~~~~
lib/templates/rspec/request/request_spec.rb: Parser::SyntaxError: unexpected token tIDENTIFIER
lib/generators/migration.rb:1:7: error: unexpected token tLT
lib/generators/migration.rb:1: class <%= migration_class_name %> < ActiveRecord::Migration[<%= ActiveRecord::Migration.current_version %>]
lib/generators/migration.rb:1:       ^
lib/generators/migration.rb: Parser::SyntaxError: unexpected token tLT
lib/generators/migration.rb:1:7: error: unexpected token tLT
lib/generators/migration.rb:1: class <%= migration_class_name %> < ActiveRecord::Migration[<%= ActiveRecord::Migration.current_version %>]
lib/generators/migration.rb:1:       ^
lib/generators/migration.rb: Parser::SyntaxError: unexpected token tLT
lib/generators/policy/templates/policy.rb:1:7: error: unexpected token tLT
lib/generators/policy/templates/policy.rb:1: class <%= file_name.classify %>Policy < ApplicationPolicy
lib/generators/policy/templates/policy.rb:1:       ^
lib/generators/policy/templates/policy.rb: Parser::SyntaxError: unexpected token tLT
lib/generators/policy/templates/policy.rb:1:7: error: unexpected token tLT
lib/generators/policy/templates/policy.rb:1: class <%= file_name.classify %>Policy < ApplicationPolicy
lib/generators/policy/templates/policy.rb:1:       ^
lib/generators/policy/templates/policy.rb: Parser::SyntaxError: unexpected token tLT
lib/templates/rails/scaffold_controller/api_controller.rb:1:1: error: unexpected token tLT
lib/templates/rails/scaffold_controller/api_controller.rb:1: <% if namespaced? -%>
lib/templates/rails/scaffold_controller/api_controller.rb:1: ^
lib/templates/rails/scaffold_controller/api_controller.rb: Parser::SyntaxError: unexpected token tLT
lib/templates/rails/scaffold_controller/api_controller.rb:1:1: error: unexpected token tLT
lib/templates/rails/scaffold_controller/api_controller.rb:1: <% if namespaced? -%>
lib/templates/rails/scaffold_controller/api_controller.rb:1: ^
lib/templates/rails/scaffold_controller/api_controller.rb: Parser::SyntaxError: unexpected token tLT
lib/templates/rspec/request/request_spec.rb:6:54: error: unexpected token tIDENTIFIER
lib/templates/rspec/request/request_spec.rb:6:   let(:org_<%=plural_table_name%>) { create_list :<%=singular_table_name%>, 3, organization: organization }
lib/templates/rspec/request/request_spec.rb:6:                                                      ^~~~~~~~~~~~~~~~~~~
lib/templates/rspec/request/request_spec.rb: Parser::SyntaxError: unexpected token tIDENTIFIER
lib/templates/rspec/request/request_spec.rb:6:54: error: unexpected token tIDENTIFIER
lib/templates/rspec/request/request_spec.rb:6:   let(:org_<%=plural_table_name%>) { create_list :<%=singular_table_name%>, 3, organization: organization }
lib/templates/rspec/request/request_spec.rb:6:                                                      ^~~~~~~~~~~~~~~~~~~
lib/templates/rspec/request/request_spec.rb: Parser::SyntaxError: unexpected token tIDENTIFIER
```

Followed by reek output

**Comment by troessner** [comment]
@Ross-Hunter Ah, ok, the ERB templates you had mentioned already. Now that's easy to see :)
Thanks for following up on this!
Let's close this issue.
